kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: sample-rest-build-config
spec:
  source:
    dockerfile: |
      FROM maven:3-openjdk-17 AS buildimg
      WORKDIR /build
      COPY complete .
      RUN mvn clean install

      FROM openjdk:17
      WORKDIR /app
      COPY --from=buildimg /build/target/rest-service-complete-0.0.1-SNAPSHOT.jar .

      EXPOSE 8080
      ENTRYPOINT ["java", "-jar", "rest-service-complete-0.0.1-SNAPSHOT.jar"]
    git:
      uri: 'git@github.com:chetansanghiwork/gs-rest-service.git'
      ref: main
    sourceSecret:
      name: github-ssh-key
  strategy:
    type: Docker
    dockerStrategy:
      noCache: true
      pullSecret:
        name: docker-io-credentials
  output:
    to:
      kind: DockerImage
      name: 'docker.io/chetangsanghi/spring-boot-rest-hello-private:1.0.0-latest'
    pushSecret:
      name: docker-io-credentials
  resources:
    limits:
      cpu: '1'
      memory: 2G